---
dist: trusty
language: node_js
node_js:
  - 6
install:
  - make install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "make start-selenium 2>&1 &"
  - sleep 5
script:
  - make build
  - make test
cache: false
branches:
  only:
    - master
